---
name: ci
on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  generate:
    name: generate
    runs-on: actuated
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15.3
      - name: Docker Build
        run: |
          docker build .
          VPP_VERSION=$(docker run $(docker build -q . --target version))
          echo "VPP_VERSION=${VPP_VERSION}" >> $GITHUB_ENV
          TAG=v${VPP_VERSION/\~/-}
          echo "TAG=${TAG}" >> $GITHUB_ENV
          docker build -t ghcr.io/${{github.repository}}/vpp:${TAG} . --target vpp
          docker build -t ghcr.io/${{github.repository}}/vpp-dbg:${TAG} . --target vpp-dbg
      - name: Generate files
        run: go generate ./...
      - name: Check for changes in generated code
        run: |
          git diff -- binapi || (echo "Rerun go generate ./... locally and resubmit" && exit -1)
      - name: Go Build
        run: go build ./...
